### PR TITLE
Show/take long break

### LINKED ISSUE #374: Display next long break
Hi,
Currently only time of next short break is displayed, optional display of next long break will be great.
Thanks

### PR DESCRIPTION
**Pull request by AdamPS**
Attempt to fix #374 and #347.  It works for me but I expect I didn't understand everything properly:-)

### CODE REVIEW

**Comment by slgobinath** [comment]
Hi, Thank you very much for your contribution. I am having a tight schedule these days so I may take some time to test this PR and merge it. Feel free to commit while the PR is open. Once I've tested the PR and reviewed the code, I will get back to you.

Thanks

**Comment by AdamPS** [comment]
OK thanks

**Comment by slgobinath** [comment]
Hi,
I reviewed the code. There are some minor issues here and there but I prefer to group the menu items to take a break manually and introduce another menu item to take only short breaks:
- Any break
- Short break
- Long break

I also noticed that the API must be changed to support these three different menu items. Therefore, I've created a new branch with the initial implementation for manual long break menu item. I will use your code and idea wherever required and highly welcome you to test the implementation and/or contribute to this branch. https://github.com/slgobinath/SafeEyes/tree/feature-long-break-friendly-tray-icon.

Currently I have the code to take any, short or long breaks. I am working on fixing the `Next break at` message to include the break type.

**Comment by AdamPS** [comment]
Thanks @slgobinath.  Your new branch makes sense and it works for me to fix #347.

> I am working on fixing the Next break at message to include the break type.
Great.  However my original branch did more than that.  I would like an option to display the time until the long break in the tray/menu - even if a short break comes first.

**Comment by slgobinath** [comment]
I'm closing this PR and lets discuss on the issue #374 about the next break information.

**Pull request closed without merging**
