### PR TITLE
add czech translation

### PR DESCRIPTION
**Pull request by HugoShamrock**
Hello,
Czech translation for SafeEyes ...

Hugo

### CODE REVIEW

**Comment by jankudrik** [comment]
@HugoShamrock Allow me to make a few suggestions for your translation. As somebody who has many years experience in English-to-Czech translations I believe this will make it look much nicer ;-)

"Zakloň se na svém křesle a relaxuj" -> "Opřete se do židle a odpočívejte"
("Zaklonit se" is not really what you do when you "lean back".)

"Přivři oči" -> "Zavřete oči"
("Přivři" is closer to "slightly" than "tightly".)

"Vyval oči" -> "Koulejte očima"
(The use of "vyval" is really funny here :-).)

"Otáčej očima ve směru hodinových ručiček" -> "Kružte očima doprava"
"Otáčej očima proti směru hodinových ručiček" -> "Kružte očima doleva"
(Generally, "doprava" and "doleva" is more commonly used when specifying directions. Also "otáčejte" suggests a bit different movement of eyes, but that may be just my personal perception.)

"Mrkej očima" -> "Zamrkejte"
(This just looks better to me.)

"Dej si nějakou vodu" -> "Napijte se"
(The same case as above.)

As you can see, I used "vykání" instead of "tykání", but you can alter that to your liking.

**Comment by jankudrik** [comment]
@HugoShamrock Another thing I noticed - "Czech" as a noun should be translated to "Čeština".

**Comment by slgobinath** [comment]
Hi @HugoShamrock and @jankudrik thanks for your contribution. As I have no experience with Czech, could you please come to an agreement on whether to include the suggestions by @HugoShamrock or not.
I leave this PR open for modification and voting by others who knows Czech. Later I will decide on merging this PR.

**Comment by HugoShamrock** [comment]
I prepare a new version today ...

Hugo

**Pull request closed without merging**
