### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by terop**

### CODE REVIEW

**Review by nifadyev — APPROVED** [review]
LGTM, thanks @terop

**Review by deltragon — APPROVED** [review]

**Comment by nifadyev** [comment]
Hey @terop , thanks for your work. How did you found these typos? I mean manually or using some tools. I would suggest fixing other typos with help of some tool in this PR, if you don't mind extra work.

**Comment by terop** [comment]
Hello @nifadyev, I use a tool called [codespell](https://github.com/codespell-project/codespell) for this.

I did a another check with codespell and no new typos came up.

**Comment by archisman-panigrahi** [comment]
Since the changes are constructive, and there is no way fixing the typos can break existing features, I am merging this without any further testing.

**Pull request merged**
