### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by Akronix**

### CODE REVIEW

**Comment by slgobinath** [comment]
Could you please resolve the conflicts.

Thanks

**Comment by Akronix** [comment]
Done :+1:

**Comment by slgobinath** [comment]
Hi @Akronix ,

Thank you very much :-)

**Comment by Akronix** [comment]
You're welcome @slgobinath, You've done a pretty good job with this small utility.

**Comment by slgobinath** [comment]
Thanks

**Pull request merged**
