### PR TITLE
Added macedonian translation

### PR DESCRIPTION
**Pull request by StefanTrajkov**

### CODE REVIEW

**Comment by orschiro** [comment]
Has this been successfully merged?

**Comment by StefanTrajkov** [comment]
No I had a very bad internet connection. I will try again tonight when I get home.

**Comment by StefanTrajkov** [comment]
I had a very bad connection so I don't know what actually happened. I think I deleted this commit because I was not sure whether everything was okay.

**Comment by orschiro** [comment]
Can you resubmit it?

It says pull request from unknown repository.

**Comment by StefanTrajkov** [comment]
Yes, I will do everything all over. Just to be sure.

**Pull request closed without merging**
