### PR TITLE
Added Catalan translation

### PR DESCRIPTION
**Pull request by davilera**

### CODE REVIEW

**Comment by slgobinath** [comment]
Hi @davilera,
Thank you for your contribution. Could you please translate [safeeyes.desktop](https://github.com/slgobinath/SafeEyes/blob/master/share/applications/safeeyes.desktop) as well. Need a new line translating the description.

**Comment by davilera** [comment]
Sure, but don't know how. Should I create a second pull request?

**Comment by slgobinath** [comment]
@davilera,
Everything is good. I am merging your PR.

FYI: Until your PR is merged, you can simply commit and push new changes to the same branch. The new commits will automatically become part of your PR.

**Comment by davilera** [comment]
Oh, great! That means that my last commit has been successfully merged too :-) Thanks, man!

**Comment by slgobinath** [comment]
Yeah!
You are welcome and thanks for translating Safe Eyes :-)

**Pull request merged**
