### PR TITLE
Support https://reuse.software/

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Hello and thanks for developing SafeEyes. Here's a little patch to support https://reuse.software/
Once merged it can help track ownership and you can get a badge.
Could you please help clarify if traslations, icons, sounds etc are under different licenses?

### CODE REVIEW

**Comment by archisman-panigrahi** [comment]
Can you please explain what this is for?

**Comment by archisman-panigrahi** [comment]
AFAIK, everything is under the same license.
Please explain why this PR is helpful for "humans and machines alike". Otherwise, I will close this in a week.

**Comment by FedericoCeratto** [comment]
The REUSE initiative makes licensing information machine parsable and reusable and encourages adoption of FOSS by removing risks of misunderstanding around licensing. The project can even be registered on https://api.reuse.software/ to show it's really compliant with the format. See the supporters and adopters at https://reuse.software/

**Comment by archisman-panigrahi** [comment]
Thank you!

**Pull request merged**
