### PR TITLE
Missing Turkish translations

### PR DESCRIPTION
**Pull request by karsibali**
There were a few missing Turkish translations since my last translation. I included those.

### CODE REVIEW

**Comment by slgobinath** [comment]
Hi,

Thanks for your PR. GitHub says that there are some conflicts. Could you please resolve them.

Thanks

**Comment by karsibali** [comment]
The conflicting file is the one I changed. The file has to be replaced by the new one. That is all.

**Comment by karsibali** [comment]
Sorry, the conflict was due to my fork not being in sync with the master branch. I synced my fork and resolved the conflicts.

**Comment by slgobinath** [comment]
Thanks, @karsibali. The PR is merged.

**Pull request merged**
