### PR TITLE
PluginManager: retry loading trayicon plugin when service is missing

### PR DESCRIPTION
**Pull request by deltragon**
## Description

Fixes https://github.com/slgobinath/SafeEyes/issues/636.

This PR implements the retry logic mentioned there.
When the trayicon plugin detects that there is no SNI DBus service running, it will retry after a few seconds.
This circumvents issues where SafeEyes is started on autostart, before the SNI service is running.

If the SNI service is still not found after multiple retries, the plugin shows the dialog with the instructions, like before.

This PR is best reviewed commit by commit - the first commit implements some refactoring needed for the second one, but should not have functional changes.

### CODE REVIEW

**Comment by deltragon** [comment]
@archisman-panigrahi 
Unfortunately, I did have to refactor `plugin_manager.py` a lot for this, and add the logic in there - as the trayicon plugin is not even loaded when the dependency is missing, it can't contain the logic for retrying.
I am not 100% happy with how this solution has turned out, if you have ideas for how to make it more self-contained, please suggest them.

**Comment by archisman-panigrahi** [comment]
The easiest way would be something like this https://github.com/slgobinath/SafeEyes/issues/636#issuecomment-2302120734, which works in the Cinnamon desktop.

However, OP says it does not work in the GNOME desktop.

----

I will definitely test your PR.

**Comment by deltragon** [comment]
Well, seeing how https://github.com/slgobinath/SafeEyes/issues/637 is the same issue, maybe it does make sense to fix this in a way that is independent of the desktop environment.

**Comment by archisman-panigrahi** [comment]
@deltragon  How many times does it retry, and what are the intervals between them?

**Comment by deltragon** [comment]
Oh yes, I meant to comment this - it currently retires 3 times, with increasing wait time (1s, 2s, 4s). So at most it waits 7 seconds before showing the dialog, but may be faster if the SNI service starts earlier.
But I'm also open to something simpler, like 2 times 5 seconds.

**Comment by archisman-panigrahi** [comment]
Sorry about my silence. I had been busy with university work. I will test and merge it this weekend.

**Review by archisman-panigrahi — APPROVED** [review]
Works as expected. Thank you so much.
I am very sorry about my delayed response.

**Pull request merged**
