### PR TITLE
Update cs and sk translations

### PR DESCRIPTION
**Pull request by radek-sprta**

### CODE REVIEW

**Comment by radek-sprta** [comment]
The commit history is bit messy, hope that's ok.

**Comment by slgobinath** [comment]
@radek-sprta and @p-bo ,
Thanks for your contribution. As @p-bo suggested, I have created the Weblate account[1] so I hope it will be easy for translators in future.
[1] https://hosted.weblate.org/projects/safe-eyes/translations/

**Comment by p-bo** [comment]
Thanks @radek-sprta for very fruitful cooperation on fine tuning localization into czech, thanks @slgobinath for provide us with way for wider contributors how to translate - nice :)
Would it be possible to point at weblate from: https://slgobinath.github.io/SafeEyes/#translate please?

**Comment by slgobinath** [comment]
@p-bo,
I am waiting for the direct PUSH feature. Oce it is available, I will update the website.

Thanks

**Comment by slgobinath** [comment]
@p-bo,
The official page is updated with the new how to translate.

**Comment by p-bo** [comment]
@slgobinath great - very explanatory and short - good work!

**Pull request merged**
