### PR TITLE
Reverse-DNS scheme for icons & Broken initialize logic fix & Add appstream

### PR DESCRIPTION
**Pull request by otuva**
Hi, this PR includes:
- ### Reverse dns named icon files
In its current form icon files cannot be exported via flatpak, so tray icon will be invisible unless there's another installation that supplies it (could be icon themes or another installation of safeeyes such as from pypi). So I renamed them according to reverse dns scheme. This is beneficial to both flatpak and general package and icons will be distinctive enough from another similar named icons (if it ever happens)
Related flathub/io.github.slgobinath.SafeEyes#1

- ### Broken initialize logic
 `initialize_safeeyes` function uses custom variable (`style_dir_path`) which uses hardcoded '.config' instead of global variable `CONFIG_DIRECTORY` thus causes function to not respect `XDG_CONFIG_HOME`.
This causes issues where `XDG_CONFIG_HOME` is not '~/.config' 

Message from https://github.com/slgobinath/SafeEyes/issues/432#issuecomment-883829334
```
Traceback (most recent call last):
  File "/app/bin/safeeyes", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.8/site-packages/safeeyes/__main__.py", line 113, in main
    config = Config()
  File "/app/lib/python3.8/site-packages/safeeyes/model.py", line 308, in __init__
    utility.initialize_safeeyes()
  File "/app/lib/python3.8/site-packages/safeeyes/utility.py", line 377, in initialize_safeeyes
    shutil.copy2(SYSTEM_CONFIG_FILE_PATH, CONFIG_FILE_PATH)
  File "/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gobinath/.var/app/org.slgobinath.SafeEyes/config/safeeyes/safeeyes.json'
```

Root cause https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/utility.py#L377

As a fix, `STYLE_SHEET_DIRECTORY` extends `CONFIG_DIRECTORY` and initialize function creates `STYLE_SHEET_DIRECTORY`

- ### Adding appstream. 

Instead of seperate PRs, I'm merging them into one. So I closed the other one

#### What is AppStream

AppStream is a cross-distro effort for enhancing the metadata available about software components in the Linux and free-software ecosystem. One of the project's goals is to make building software-center applications possible, and make interaction with the package sources of a distribution smarter.

#### File system locations

Upstream projects can ship one or more metainfo files in `/usr/share/metainfo/%{id}.metainfo.xml`, where ID is a unique identifier of this specific component. 

#### ID 

The ID tag is a unique identifier for this component. It must contain only alphanumeric ASCII characters, dots, hyphens and underscores. Spaces are not allowed

The ID must follow a reverse-DNS scheme, consisting of {tld}.{vendor}.{product}, for example `org.kde.gwenview` or `com.hugski.colorhug2`. Ownership of {vendor}.{tld} in the domain name system guarantees uniqueness of IDs.

#### Motivation 

New [flatpak package](https://flathub.org/apps/details/io.github.slgobinath.SafeEyes) already uses provided metainfo. It would be cool to provide cross-distro identification. Even though I did not write the code for it, I can if you want. 

---

Looking forward to your feedback :)

### CODE REVIEW

**Comment by otuva** [comment]
@slgobinath sorry to bother you but do you mind taking a look? In its ongoing state, UX is not good for flatpak package

**Comment by slgobinath** [comment]
Thanks, @otuva for your contribution. It looks good to me.
@hartwork do you have any comments?

**Review by hartwork — COMMENTED** [review]
> @hartwork do you have any comments?

Hi @slgobinath,

I'm rather critical of flatpak due to their [dependency bundling](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies) and their advertising of a non-sandbox as a sandbox, both of which are not ideal for end-user security in my book.
Because of that bias, I will not do further review in detail — I hope that's okay. The one thing I do want to say more on this is that the badge about to be added here…

> flathub-badge

…is very loud and as a result can be interpreted as a clear official recommendation for use of/through flatpak by the SafeEyes project. So adding that badge is political, and it should be a conscious decision, one way or another.

That being said, @otuva probably has the best intentions with this and https://github.com/flathub/io.github.slgobinath.SafeEyes looks like hard work.

Best, Sebastian

**Comment by otuva** [comment]
Hello again @slgobinath, what do you think about the badge? Should it stay, should it be resized, or should it be changed with a command?

**Comment by slgobinath** [comment]
Sorry for my late comments :pray:

**Comment by hartwork** [comment]
> [..] and add a smaller badge with a hyperlink to the top

Unless there are official badges in that format, https://shields.io/ may help to create one, `logo=flatpak` seems to work, just tried.

**Comment by otuva** [comment]
> I sincerely thank @otuva for Flatpak support

Don't even mention it :) I thank _you_ for this great app 

> Sorry for my late comments

No problem at all

---

With the latest commit, I think README looks pretty consistent

**Comment by hartwork** [comment]
> With the latest commit, I think README looks pretty consistent

@otuva I agree, well done

**Comment by otuva** [comment]
Hello again @slgobinath, if everything is ok, do you mind merging this one?

**Pull request merged**
