### PR TITLE
Fix for GNOME restart

### PR DESCRIPTION
**Pull request by muazamkamal**
Moved fullscreen before present.

Possible fix for #392

### CODE REVIEW

**Comment by Xanewok** [comment]
I can confirm the fix. Some info on my setup:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
$ gnome-shell --version
GNOME Shell 3.38.1
$ apt-cache policy libgtk-3-0
libgtk-3-0:
  Installed: 3.24.23-1ubuntu1
  Candidate: 3.24.23-1ubuntu1
  Version table:
 *** 3.24.23-1ubuntu1 500
        500 http://pl.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
```

I tried to test it across multiple desktop environments, e.g. Xfce 4.14 (`xubuntu-desktop`), Unity 7.5 (`ubuntu-unity-desktop`), KDE Plasma 5 (`kubuntu-desktop`) and most importantly Gnome Shell 3.38.1 (`gnome-desktop`) and it seems the issue is resolved.

@slgobinath would you have a moment to review this at your leisure, of course? Optionally, do you have any pointers on how to properly install the local (modified) Python package globally? Thanks!

**Comment by muazamkamal** [comment]
Can you help confirm the break screen flickering (after applying this PR fix)? It happens to me, and similar to the Unity issue, it's fixed by setting the window opacity to 0.9.

If you can confirm that, I'll update this PR to fix that too.

Also, if you install through Ubuntu PPA, you can find it in `/usr/lib/python3/dist-packages/safeeyes`. The break screen file (`BreakScreen.py`) is in the root, rather than in `ui`.

**Comment by Xanewok** [comment]
I don't think I encounter flickering, in the sense that it toggles on, then off for a split second, then on again. What I'm experiencing is a black screen appearing at 90-95% display size and then smoothly resizing to the full screen. It happens relatively fast, do you mean that? The effect is less pronounced visually if I apply 90% opacity but it l think it uses the same mechanism. All of this is tested on gnome shell.

> Also, if you install through Ubuntu PPA, you can find it in /usr/lib/python3/dist-packages/safeeyes

Oh nice! I tried to find it, thanks :smile:

**Comment by hashstat** [comment]
I can confirm that this patch also fixed gnome-shell 3.38.1 crashing on my Arch Linux system.

**Comment by kg6gfq** [comment]
I came looking for a fix for this issue in Gnome 3 on Ubuntu 20.10.  Thank you for providing one!  Substituting the revised BreakScreen.py per muazamkamal's tip solves it nicely, though I had to change "utility" to "Utility" in several places.  

No flickering for me - the break screen appears to expand out from the center of the screen and contract back into the center afterwards.

**Comment by slgobinath** [comment]
@muazamkamal thank you very much for taking your time to fix the issue.

@Xanewok thank you very much for testing the fix on different environments.

In the early days I had issues with when to move the screen to a given display and when to make it full screen. Some desktop environments had issues with the order of these operations especially in a multi-monitor setup. I will test the fix using my VM machines and merge the fix after some testing.

Meanwhile, you can test/install this fix using the following command:

```shell
git clone https://github.com/slgobinath/SafeEyes.git
cd SafeEyes
git fetch origin pull/393/head:fix-gnome
git checkout fix-gnome

# To run from source, quit your running Safe Eyes instance and run the following command
python3 -m safeeyes

# To install from source, uninstall your existing installation and run the following command. You may need to keep the dependencies though.
python3 setup.py install
```

Personally, I don't prefer to install from source. Instead, I'd run from source by creating a startup shortcut.

@all thank you very much for testing this fix. I am glad these many people contributing to Safe Eyes. These days, I am little busy with my personal stuff and work but I am pushing myself to release the next version before next year (hopefully I can use my Christmas holidays). I do have plans to work on other fixes too. Hope I will meet the deadline.

**Comment by slgobinath** [comment]
Tested on Linux Mint with Cinnamon and Elementary OS. It fixes moving to a new workspace in Elementary OS too https://github.com/slgobinath/SafeEyes/issues/337

@muazamkamal thank you for the fix

**Pull request merged**
